export const SEARCH_DATA_ACTION_TYPES = {
  FETCH_SEARCH_DATA_START: "FETCH_SEARCH_DATA",
  FETCH_SEARCH_DATA_SUCCESS: "FETCH_SEARCH_DATA_SUCCESS",
  FETCH_SEARCH_DATA_ERROR: "FETCH_SEARCH_DATA_ERROR",
};
