export const TRANSACTION_ACTION_TYPES = {
  FETCH_TRANSACTIONS_START: "FETCH_TRANSACTIONS_START",
  FETCH_TRANSACTIONS_SUCCESS: "FETCH_TRANSACTIONS_SUCCESS",
  FETCH_TRANSACTIONS_ERROR: "FETCH_TRANSACTIONS_ERROR",
};
